name: Mahasiswa-Simak-Client

on:
  push:
    branches:
      - main # Execute on every push
  workflow_dispatch: # Execute on manual trigger

jobs:
  build-and-start:
    runs-on: ubuntu-latest # Linux base image
    steps:
      - uses: actions/checkout@v4 # Checkout repo
      - uses: oven-sh/setup-bun@v1 # Setup bun
        with:
            bun-version: latest # You can also use a specific version
      - run: bun install # Only needed if you have any dependencies
      - run: bun run build:production  # Change to your entrypoint!
      - name: Publish to npm
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.TOKEN }}
