name: vtocph23

on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Checkout repo
      - uses: oven-sh/setup-bun@v1 # Setup bun
        with:
          bun-version: latest # You can also use a specific version
      - run: bun install # Only needed if you have any dependencies
      - run: npm publish --access=public
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.TOKEN }}
